---
description: "sensu-nodejs-plugins"
builds:
  - platform: "linux"
    arch: "amd64"
    asset_filename: "sensu-nodejs-plugins-alpine.tar.gz"
    sha_filename: "sensu-nodejs-plugins-alpine_sha512_checksums.txt"
    filter:
      - "entity.system.os == 'linux'"
      - "entity.system.arch == 'amd64'"
      - "entity.system.platform == 'alpine'"
